name: CD - Deploy via FTP (after CI)

on:
  workflow_run:
    workflows: ["CI - Symfony"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # On ne déploie que si la CI a réussi ET sur la branche develop
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_mysql

      # Installation propre pour la prod
      - name: Install dependencies (prod)
        run: composer install --no-dev --optimize-autoloader --no-scripts

      # Nettoyage du cache Symfony
      - name: Clear and warm cache
        run: |
          APP_ENV=prod APP_DEBUG=0 php bin/console cache:clear
          APP_ENV=prod APP_DEBUG=0 php bin/console cache:warmup

      # Déploiement FTP
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: ./  
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/tests/**
            **/DataFixtures/**
            **/var/**


