name: deployement
on:
    workflow_run:
        workflows: ["CI - Symfony"]
        types: [completed]

jobs:
    deploy:
        if: >
            github.event.workflow_run.conclusion == 'success' &&
            github.event.workflow_run.head_branch == 'master'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: composer install --no-interaction --prefer-dist --no-progress --ignore-platform-req=ext-redis
            - name: Deploy
              uses: SamKirkland/FTP-Deploy-Action@v4.3.6
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  exclude: |
                      var/**
                      **/.git*
                      **/.git*/**
