name: CI - Symfony

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --no-interaction

      - name: Run PHPUnit tests
        run: |
          if [ -d "tests" ]; then
            php bin/phpunit --testdox
          else
            echo "Aucun test trouvé, exécution ignorée."
          fi
